version: 2
updates:
  - package-ecosystem: "nuget" # .NET dependencies
    directory: "/todo-api-1/src" # Correct directory containing .sln and .csproj files
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
