version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directories:
      - "todo-api-1/src/TodoAPI"
      - "todo-api-1/src/TodoAPI.Tests"
      - "todo-api-1/src/TodoWebapp"
      - ".github/workflows/todo-api.yaml"
      - "deploy/terraform/todo-api/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
